# Tomcat
server.port: 80

# QQ
qq:
  appId: 101419871
  appSecret: 2c66********************24bd
  appCallback: http://api.incarcloud.com/3rd/qq

# AliYun
aliyun:
  accountId: 1786089012649873
  accessKeyId: qkjiPJf7YkkYhW39
  accessKeySecret: ruk******qPT
  OTS:
    endpoint: http://gate-way.cn-hangzhou.ots-internal.aliyuncs.com

# GateWay
gateway:
  # 前端网站域名(CORS)
  sites:
    - http://my.incarcloud.com
  # 数据存储引擎类型
  repo: AliYunOTS